### ISSUE TITLE
seeding method rework

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-seedcalc#119]
**What's wrong**
- it says not recommended twice for `Aerial(or broadcast with no Light Incorporation Not Recommended):`, it should only show not recommended in the right column
- i think all the coefficients might be hard hardcoded instead of fetched from the api
- the coefficient should be used in the later steps as `Management impact on mix`, that value is hardcoded as 0.5 currently
- the modifier should be shown in the dropdown (ex: Precision (0.9))

**What done looks like**
- fix the above

**Comment by YazidZidane** [comment]
- I think the Not Recommended for `Aerial` is for MCCC since only in MCCC the coefficients are available.
- All the coefficients are fetched from the api but they are all the same for all crops in MCCC.
- The dropdown and Mix Seeding Rate(the vertical slider) are both for adjusting `Management impact on mix`, do we need to apply the changes for the dropdown to the slider?

**Comment by mikahpinegar** [comment]
- if aerial is only used for the MCCC then it shouldn't be shown for NECCC
- the coefficients look correct for the MCCC but for the NECCC drilled should have a value of one and be recommended for almost every crop but it's showing not recommended. something is broken for the NECCC
- i don't think the slider should change the `Management impact on mix` it should adjust the total mix. only the dropdown should adjust the `Management impact on mix` which is then used to multiply the total mix
