### ISSUE TITLE
Redesign the seed data chip

### ISSUE THREAD

**Issue by YazidZidane** [precision-sustainable-ag/dst-seedcalc#140]
**What's wrong**
- Currently the data chip is confusing

**What done looks like**
- Separate plants per sqft/acre and seeds per sqft/acre
- remember the unit across the app

**Where the changes need to be made**
- SeedingRateCard

**Comment by mikahpinegar** [comment]
i think this new view is more confusing because it has too much information. i think the old design was good but it needed to have a a column added to both sides. in the screenshot below the styling would stay the same but the right would get seeds per acre or sqft added and the left would get plants per acre or sqft added and they would both still have a toggle for sqft and acres.

the toggle should apply to all plants in the column. so if i change the units for `Default Single Species Seeding Rate PLS` for one species it should change for the others as well. the same should happen to `Default Seeding Rate in Mix`. 

![units](https://github.com/precision-sustainable-ag/dst-seedcalc/assets/55995241/6111eb37-1cb6-4248-b7a5-aea601d980a5)
